(function($,window){
  'use strict';
  const ROOT='#luhmCockpit',VIEWER='[data-luhm-proof-viewer]';
  const TYPES=new Set(['pdf','docx','website','image','asset','json','text']);
  const STATUSES=new Set(['GREEN','AMBER','RED','UNKNOWN']);
  let current=null;
  function clean(v,max){return String(v==null?'':v).replace(/[<>]/g,'').slice(0,max||4000)}
  function safeUrl(value,allowBlob){if(!value)return'';try{const u=new URL(String(value),window.location.href);const p=u.protocol.toLowerCase();if(p==='https:')return u.href;if(p==='blob:'&&allowBlob!==false)return u.href;if(p==='http:'&&u.origin===window.location.origin)return u.href}catch(_e){}return''}
  function normalize(d){if(!d||typeof d!=='object')throw new Error('proof packet must be object');const type=clean(d.type,20).toLowerCase();if(!TYPES.has(type))throw new Error('unsupported proof type');const id=clean(d.id,120);if(!id)throw new Error('proof id missing');let status=clean(d.status||'UNKNOWN',16).toUpperCase();if(!STATUSES.has(status))status='UNKNOWN';return{id,type,title:clean(d.title||'Proof',180),status,sourceRef:clean(d.sourceRef||'UNKNOWN',160),sha256:clean(d.sha256||'UNKNOWN',96),provenance:clean(d.provenance||'UNKNOWN',180),capturedAt:clean(d.capturedAt||'',80),url:safeUrl(d.url,true),snapshotUrl:safeUrl(d.snapshotUrl,true),liveUrl:safeUrl(d.liveUrl,false),allowLive:d.allowLive===true,blocks:Array.isArray(d.blocks)?d.blocks.slice(0,500):[],data:d.data,text:clean(d.text||'',200000),fields:d.fields&&typeof d.fields==='object'?d.fields:{},mime:clean(d.mime||'',100)} }
  function $viewer(){return $(ROOT).find(VIEWER).first()}function $stage(){return $viewer().find('[data-proof-stage]').first()}
  function meta(label,value,code){const $c=$('<div>',{'class':'proofMetaCell'});$('<small>',{text:label}).appendTo($c);$(code?'<code>':'<span>').text(clean(value||'UNKNOWN',180)).appendTo($c);return $c}
  function renderMeta(p){const $v=$viewer();$v.find('[data-proof-kind]').text(p.type.toUpperCase());$v.find('[data-proof-title]').text(p.title);$v.find('[data-proof-status]').attr('data-status',p.status).text(p.status);const $m=$v.find('[data-proof-meta]').empty();$m.append(meta('source',p.sourceRef,true),meta('sha256',p.sha256,true),meta('provenance',p.provenance,false),meta('captured',p.capturedAt||'UNKNOWN',false))}
  function empty(t){$stage().append($('<div>',{'class':'proofEmpty',text:t}))}
  function renderImage(p,u){if(!u)return empty('No safe image preview URL supplied.');const $w=$('<div>',{'class':'proofImageWrap'});$('<img>',{src:u,alt:p.title,referrerpolicy:'no-referrer'}).on('error',()=>{$w.empty().append($('<div>',{'class':'proofEmpty',text:'Image preview failed.'}))}).appendTo($w);$stage().append($w)}
  function renderPdf(p){if(!p.url)return empty('No safe PDF URL supplied.');const $o=$('<object>',{'class':'proofPdf',type:'application/pdf',data:p.url});$('<p>',{text:'Embedded PDF preview unavailable in this WebView.'}).appendTo($o);$stage().append($o)}
  function docBlock($d,b){if(!b||typeof b!=='object')return;const t=clean(b.type||'paragraph',24).toLowerCase(),v=clean(b.text||'',20000);if(t==='heading'){const n=Math.max(1,Math.min(3,Number(b.level)||2));$('<h'+n+'>',{text:v}).appendTo($d)}else if(t==='quote')$('<blockquote>',{text:v}).appendTo($d);else if(t==='code')$('<pre>').append($('<code>',{text:v})).appendTo($d);else if(t==='list'){const $l=$('<'+(b.ordered?'ol':'ul')+'>');(Array.isArray(b.items)?b.items:[]).slice(0,200).forEach(x=>$('<li>',{text:clean(x,5000)}).appendTo($l));$l.appendTo($d)}else if(t==='table'){const $t=$('<table>');(Array.isArray(b.rows)?b.rows:[]).slice(0,100).forEach((r,ri)=>{const $tr=$('<tr>').appendTo($t);(Array.isArray(r)?r:[]).slice(0,20).forEach(c=>$('<'+(ri===0&&b.header!==false?'th':'td')+'>',{text:clean(c,4000)}).appendTo($tr))});$t.appendTo($d)}else $('<p>',{text:v}).appendTo($d)}
  function renderDocx(p){const $d=$('<article>',{'class':'proofDoc'});if(!p.blocks.length)$('<p>',{text:'DOCX has no structured preview blocks. Raw Office HTML is never executed.'}).appendTo($d);else p.blocks.forEach(b=>docBlock($d,b));$stage().append($d)}
  function renderWebsite(p){const $w=$('<div>',{'class':'proofWebsite'});if(p.snapshotUrl)$('<img>',{'class':'proofWebsiteShot',src:p.snapshotUrl,alt:p.title+' snapshot',referrerpolicy:'no-referrer'}).appendTo($w);if(p.allowLive&&p.liveUrl)$('<iframe>',{'class':'proofWebsiteFrame',src:p.liveUrl,title:p.title+' sandboxed website',sandbox:'',referrerpolicy:'no-referrer'}).appendTo($w);if(!p.snapshotUrl&&!(p.allowLive&&p.liveUrl))$('<div>',{'class':'proofEmpty',text:'No captured website snapshot. Live mode requires explicit opt-in.'}).appendTo($w);$stage().append($w)}
  function renderText(p,jsonMode){let v=p.text;if(jsonMode){try{v=JSON.stringify(p.data==null?{}:p.data,null,2)}catch(_e){v='{}'}}$('<pre>',{'class':'proofText',text:v||'(empty proof)'}).appendTo($stage())}
  function renderAsset(p){const $w=$('<section>',{'class':'proofAsset'}),$pre=$('<div>',{'class':'proofAssetPreview'}).appendTo($w);if(p.url)$('<img>',{src:p.url,alt:p.title,referrerpolicy:'no-referrer'}).appendTo($pre);else $('<span>',{text:'No visual preview'}).appendTo($pre);const $g=$('<div>',{'class':'proofAssetGrid'}).appendTo($w);Object.keys(p.fields).slice(0,24).forEach(k=>{const $c=$('<div>',{'class':'proofAssetCell'}).appendTo($g);$('<small>',{text:clean(k,60)}).appendTo($c);$('<code>',{text:clean(p.fields[k],1000)}).appendTo($c)});$stage().append($w)}
  function render(p){renderMeta(p);$stage().empty();if(p.type==='pdf')renderPdf(p);else if(p.type==='docx')renderDocx(p);else if(p.type==='website')renderWebsite(p);else if(p.type==='image')renderImage(p,p.snapshotUrl||p.url);else if(p.type==='asset')renderAsset(p);else if(p.type==='json')renderText(p,true);else renderText(p,false)}
  function open(detail){current=normalize(detail);render(current);$viewer().prop('hidden',false);$(ROOT).trigger('luhm:proof:opened',[Object.assign({},current)]);return Object.assign({},current)}
  function close(){current=null;$viewer().prop('hidden',true);$stage().empty()}
  $(function(){const $r=$(ROOT);$r.on('click','[data-proof-close]',close);$r.on('click','[data-proof-pin]',()=>{if(current&&window.LuHmBridge)window.LuHmBridge.send('proof.pin',{id:current.id,type:current.type,sourceRef:current.sourceRef,sha256:current.sha256})});window.addEventListener('luhm:native:proof-imported',e=>{try{open(e.detail||{})}catch(err){console.warn('LuHm proof rejected',err.message)}});window.addEventListener('luhm:native:proof-error',e=>console.warn('LuHm proof import error',e.detail?.reason||'unknown'));window.luhmProofViewer=Object.freeze({version:'0.2.0',open,close,current:()=>current?Object.assign({},current):null})})
})(jQuery,window);
