import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const source = resolve(root, "node_modules/jquery/dist/jquery.min.js");
const licenseSource = resolve(root, "node_modules/jquery/LICENSE.txt");
const vendorDir = resolve(root, "vendor");
const target = resolve(vendorDir, "jquery-3.7.1.min.js");
const licenseTarget = resolve(vendorDir, "jquery-LICENSE.txt");

await mkdir(vendorDir, { recursive: true });
await copyFile(source, target);
await copyFile(licenseSource, licenseTarget);

const banner = "Generated by npm run stage:jquery from exact dependency jquery@3.7.1. Do not hand-edit.\n";
await writeFile(resolve(vendorDir, "README.txt"), banner, "utf8");

const packageText = await readFile(resolve(root, "package.json"), "utf8");
if (!packageText.includes('"jquery": "3.7.1"')) {
  throw new Error("jQuery dependency is not pinned to 3.7.1");
}
console.log(`staged ${target}`);
